version: '3'
services:
  mysql-master:
    image: docker.io/mysql:5.6
    container_name: mysql-master
    restart: always
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    volumes:
    - ./data:/var/lib/mysql
    - ./conf/my.cnf:/etc/mysql/my.cnf
    privileged: true